# Generated by Django 5.1.6 on 2025-03-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
